import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'posaunehm' at '16/12/08 18:19' with Gradle 2.10
 *
 * @author posaunehm, @date 16/12/08 18:19
 */
public class LibraryTest {

}
